name: wgbs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.3
  - atk=2.36.0
  - atk-1.0=2.36.0
  - binutils_impl_linux-64=2.34
  - binutils_linux-64=2.34
  - boost=1.66.0
  - boost-cpp=1.66.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2020.6.20
  - chrpath=0.16
  - curl=7.71.1
  - cutadapt=2.10
  - dbus=1.13.6
  - dnaio=0.4.2
  - erne=2.1.1
  - expat=2.2.9
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.13.1
  - freetype=2.10.2
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gdk-pixbuf=2.38.2
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - giflib=5.2.1
  - glib=2.58.3
  - gnuplot=5.2.6
  - gobject-introspection=1.64.1
  - graphite2=1.3.13
  - graphviz=2.40.1
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gtk2=2.24.31
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=2.4.0
  - htslib=1.9
  - icu=58.2
  - jpeg=9d
  - krb5=1.17.1
  - lcms2=2.11
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgd=2.2.5
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.9.2
  - methyldackel=0.4.0
  - ncurses=6.1
  - numpy=1.19.1
  - openjdk=11.0.8
  - openssl=1.1.1g
  - pango=1.40.14
  - pcre=8.44
  - perl=5.30.3
  - picard=2.23.3
  - pigz=2.3.4
  - pip=20.2.2
  - pixman=0.38.0
  - pthread-stubs=0.4
  - pysam=0.16.0.1
  - python=3.6.7
  - python_abi=3.6
  - qt=5.9.7
  - r-base=3.4.3
  - readline=7.0
  - samtools=1.9
  - segemehl=0.3.4
  - setuptools=49.6.0
  - sqlite=3.28.0
  - tk=8.6.10
  - tktable=2.10
  - wheel=0.35.1
  - xopen=0.9.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
